[theme]
primaryColor = "#00A651"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#F0F9FF"
textColor = "#333333"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
